
if (TARGET jsoncpp_static)
if (NOT TARGET JsonCpp::JsonCpp)
    add_library(JsonCpp::JsonCpp INTERFACE IMPORTED)
    if (TARGET jsoncpp_static)
    set_target_properties(JsonCpp::JsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_static")
        add_library(JsonCpp::JsonCpp INTERFACE IMPORTED)
elseif (TARGET jsoncpp_lib)
        set_target_properties(JsonCpp::JsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_static")
    add_library(JsonCpp::JsonCpp INTERFACE IMPORTED)
    elseif (TARGET jsoncpp_lib)
    set_target_properties(JsonCpp::JsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_lib")
        add_library(JsonCpp::JsonCpp INTERFACE IMPORTED)
endif ()
        set_target_properties(JsonCpp::JsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_lib")
    endif ()
endif ()